Added source capability
browserstack/jest-js-browserstack pull request #18
Opened 2022-09-26 08:12 UTC by agarneha1331

2022-09-27 05:39 UTC, 07souravkunda approved these changes

2022-10-04 09:49 UTC, 07souravkunda submitted a review, later dismissed

2022-10-04 11:49 UTC, karanshah-browserstack requested changes

2022-10-04 11:49 UTC, karanshah-browserstack commented on browserstack.yml
> +source: jest-js:sample-master:v1.0
sample-main

2022-10-04 11:50 UTC, karanshah-browserstack approved these changes

2022-10-04 11:50 UTC, merged