JestJS BrowserStack documentation
browserstack/jest-js-browserstack pull request #2
Opened 2022-03-15 19:47 UTC by NightWing1998

2022-03-16 08:01 UTC, Archish27 requested changes
Please format the document. Also, add 2 spaces indentation in all files.

2022-03-16 08:01 UTC, Archish27 commented on src/single.test.js
> +		accessKey = process.env.BROWSERSTACK_ACCESS_KEY || "";
Declare separate varaibles

2022-03-25 14:30 UTC, Archish27 approved these changes
Can you run formatter on this project. looks like filr

2022-03-25 14:30 UTC, Archish27 commented
Merge conflicts

2022-03-25 14:31 UTC, Archish27 requested changes
merge conflicts

2022-04-05 12:25 UTC, Archish27 approved these changes

2022-04-05 14:27 UTC, asambstack commented on src/parallel.test.js
> +        await driver.sleep(1500);
Why not use something like
`await driver.wait(until.elementLocated());`

2022-04-05 14:29 UTC, asambstack commented on conf/single.conf.js
> +  "browserstack.selenium_version": "3.6.0",
Is this required?

2022-04-05 15:03 UTC, merged